### ISSUE TITLE
Immutable JSON?

### ISSUE THREAD

**Issue by handrews** [marksparkza/jschon#110]
_Original comment, but see next comment:_ The experimental implementations of JSONPatch operations on the `JSON` class are an interesting and useful idea, but they prevent users of `JSON` instances from having any reliable expectation of immutability.

Would it make sense to split these out into a `MutableJSON` mixin?

**Comment by handrews** [comment]
On further thought, immutability isn't guaranteed even without the operations (obviously... was not thinking it through yesterday), so maybe an immutable mixin is more of a possible future enhancement

**Comment by marksparkza** [comment]
> immutability isn't guaranteed

Indeed, to be strictly immutable it would really have to define a `__new__` constructor rather than `__init__`.

I did spend a lot of time staring at the JSON class and thinking 'this could / should be immutable' and wondering how to enforce immutability even for JSONSchema (inlining some of the bootstrap keywords, for example, so that JSONSchema.uri etc wouldn't have to be set from the outside). Having an immutable base class and complex, mutable derived classes gets complicated. Interestingly, it was my jschon-translation package that finally put the nail in the coffin of immutability - instances of `class JSONTranslationSchema(JSONSchema)` hold state that is dynamically updated by custom keywords. This in turn encouraged me to go forth and implement `__setitem__`, `__delitem__` and `insert` on JSON, which I had always envisaged as useful features for a JSON class.

**Comment by handrews** [comment]
Makes sense — thanks for the explanation!
