### ISSUE TITLE
Add support for +/- notation to relative JSON pointers

### ISSUE THREAD

**Issue by marksparkza** [marksparkza/jschon#23]
The current relative JSON pointer implementation is based on an outdated draft.

See https://datatracker.ietf.org/doc/html/draft-bhutton-relative-json-pointer-00 for the updated syntax.

**Comment by handrews** [comment]
I've been looking at this as an easier first PR before tackling unknown keywords, and noticed that the use of `0` as a manipulation complicates things substantially.  At least it does if you want to preserve the distinction between `0+0` and `0-0` on a round trip from string to class and back to string.

I cannot recall why it was allowed, and suspect it was a mistake.  I can include support for it, or just implement it for non-zero integers and document the limitation.  @marksparkza do you have a preference?  It's not that hard to support `0` but it makes the code a lot more fiddly.

**Comment by handrews** [comment]
So it turns out there are a number of weirdnesses and omissions in the index adjustment spec language.  I'm going to proceed as if [this branch](https://github.com/handrews/json-schema-spec/compare/main...handrews:json-schema-spec:relptr-more-fixes) gets checked in and published, and if it does not we can change it further.

**Comment by marksparkza** [comment]
@handrews, thanks for taking this on, and I agree with the proposed spec changes.
