### ISSUE TITLE
Configure annotations

### ISSUE THREAD

**Issue by jugaadi** [marksparkza/jschon#32]
Since a schema may hold annotations useful to different tools, it would be really helpful if we can specify the annotations that needs to be included or excluded for processing. This way, all the irrelevant annotations can be filtered out while initialising the schema.

**Comment by marksparkza** [comment]
If I'm understanding you correctly, I think we could achieve the outcome you're looking for by filtering the output. So if you're only interested in `title` and `description` annotations, we might do something like this:

```py
result = JSONSchema(schema).evaluate(JSON(data))
output = result.output('basic', annotations=['title', 'description'])
```

It's not really feasible to exclude keywords at the schema level, because in general that might lead to incorrect / unexpected results. For example, the result of `unevaluatedProperties` depends on annotations produced by `properties` and other keywords.

Would output filtering work in your case?

**Comment by jugaadi** [comment]
Absolutely.. This should definitely work.. Thanks.

**Comment by marksparkza** [comment]
OK, this will be in the next release.

I've only enabled filtering for the 'basic' output format. I'm hesitant to do it for either 'detailed' because it's not clear how this would work, or 'verbose' because I think by definition 'verbose' should output everything. But let me know if filtering of 'detailed' and/or 'verbose' would be useful in any way in your use case. It can be done.
