### ISSUE TITLE
Inspecting the state of the catalog before calling `create_metaschema` corrupts the catalog.

### ISSUE THREAD

**Issue by fxdgear** [marksparkza/jschon#40]
when following the example provided in the docs: https://jschon.readthedocs.io/en/latest/examples/extending_json_schema.html

I was trying to understand how a metaschema differs from a schema. 

I wanted to know what a schema looks like before and after the call to `create_metaschema`. 

Well as it turns out if you call 
```python
schema = catalog.get_schema(URI("https://example.com/enumRef/enumRef-metaschema"))
```
before calling 
```
catalog.create_metaschema(
    URI("https://example.com/enumRef/enumRef-metaschema"),
    URI("https://json-schema.org/draft/2020-12/vocab/core"),
    URI("https://json-schema.org/draft/2020-12/vocab/applicator"),
    URI("https://json-schema.org/draft/2020-12/vocab/unevaluated"),
    URI("https://json-schema.org/draft/2020-12/vocab/validation"),
    URI("https://json-schema.org/draft/2020-12/vocab/format-annotation"),
    URI("https://json-schema.org/draft/2020-12/vocab/meta-data"),
    URI("https://json-schema.org/draft/2020-12/vocab/content"),
    URI("https://example.com/enumRef"),
)
```

it ends up breaking the example. 

1. the enumRef-metaschema never gets registered as a metaschema. 
2. The validations all fail (both the valid json example as well as the invalid json example). 

This seems wrong.... I don't know whats happening inside the catalog, but inspecting the catalog state should not break it!

This is related to: https://github.com/marksparkza/jschon/issues/39

**Comment by marksparkza** [comment]
I'm not sure what you are doing but when I added the line
```
schema = catalog.get_schema(URI("https://example.com/enumRef/enumRef-metaschema"))
```
before the line
```
catalog.create_metaschema(
```
in the example, it still worked fine.

Did you clone the full source tree? To run this example, the data files referred to in the docs need to be present.

In any case, I worked through what happens in the catalog with the above change. What happens is that the schema created by the line you added gets cached in the `default` cache (which is normal for a regular JSONSchema), while the Metaschema created by catalog.create_metaschema is cached in the internal `__meta__` cache. When the validations run, the schema looks up its metaschema in the `__meta__` cache, so even though there is a JSONSchema object with the same URI as the Metaschema, it's not in the metaschema cache and so doesn't interfere with metaschema resolution.

**Comment by fxdgear** [comment]
> Did you clone the full source tree? To run this example, the data files referred to in the docs need to be present.

No I didn't I just created the files locally (some copy paste). 

---

re working through the example... so it doesn't seem to be corrupted then but that there's some hidden complexities about the different caches that are getting their wires crossed? 

Did I understand that fully? 

Anyway I'll let you decide if you wanna close this, or if you think it's worth keeping open.

**Comment by marksparkza** [comment]
OK, I understand where the confusion is coming from, and I've improved the bahaviour of `Catalog.get_schema` as a result. So while I think 'corrupted catalog' was a bit of a stretch, I appreciate your inquiring about inexplicable behaviour and yes - there is a hidden complexity which I've now removed, so thanks!

Here's what's happening:

If you call `catalog.get_schema(URI("https://example.com/enumRef/enumRef-metaschema"))` before `catalog.create_metaschema`, then you're creating and retrieving a JSONSchema instance, that is cached in the `'default'` cache.

If you call `catalog.get_schema(URI("https://example.com/enumRef/enumRef-metaschema"))` _after_ `catalog.create_metaschema`, then you're retrieving the metaschema that's been cached in the `'__meta__'` cache. Internally, if `get_schema` does not find the schema in the cache identified by `session=` (`'default'` by default), then it will 'fall through' to looking in the `'__meta__'` cache, in this case finding a schema identified by that URI in the latter cache, and returning the Metaschema instance to you.

If you call `catalog.get_schema(URI("https://example.com/enumRef/enumRef-metaschema"))`both before _and_ after `catalog.create_metaschema`, then the after call will find the JSONSchema instance that's in the `'default'` cache.

It turns out that the implicit fall through behaviour is unnecessary. So in the next release you'll find that `catalog.get_schema(URI("https://example.com/enumRef/enumRef-metaschema"))`will always return a JSONSchema instance (loading it if not already cached), and you'll have to call `catalog.get_schema(URI("https://example.com/enumRef/enumRef-metaschema"), cacheid='__meta__')`to get the Metaschema instance. The `session` parameter has been renamed to `cacheid`, which is what it is.

**Comment by fxdgear** [comment]
@marksparkza great thanks! 

Corrupt is indeed the wrong word now that I understand what’s happening. :)
